### ISSUE TITLE
base_partner_app

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/partner-contact#1]
Menu partner seperti Odoo lawas (<= 6.0) lebih memudahkan dalam implementasi konsep partner dalam Odoo. Berapa menu seperti: (1) state, (2) country, (3) bank, dll juga akan lebih baik (IMHO) jika digabungkan dalam satu menu utama. Usulan struktur menu di partner management:
1. Partner
   
   1.1 Corporate Partner
   1.2 Individual Partner
2. Reporting
3. Configuration
   
   3.1 Address
   
     3.1.1 Countries
     3.1.2 States
     3.1.3 Cities/Locations
   
   3.2 Bank
   
     3.2.1 Bank Accounts
     3.2.2 Banks
     3.2.3 Bank Account Types

Dependensi cukup ke base

**Comment by andhit-r** [comment]
Gimana @azmimr67 @mikevhe18 ? Setuju?

**Comment by mikevhe18** [comment]
@andhit-r Mas, untuk menu "**Cities/Locations**" itu khan pake modul dari oca "**base_location**", jadinya akan perlu nambah depedencies. Itu gmna mas ?

Trus untuk menu "**Reporting**", isinya apa mas ?

**Comment by azmimr67** [comment]
Saya belum melihat pemisahan individual dan company menjadi isu utama karna
pembedanya hanya iscompany. Karna ini hanya mempermudah pemisahan saja.
Namun untuk kepentingan di module lainnya yang mengambil info dari partner
saya tidak melihat ada advantage dengab pemisahan tsb. Saya pikir tidak
perlu dipisah. Mungkin lebih baik fokus yang lain.
